# snpArcher v2 test configuration

samples: "config/samples.csv"

reference:
  name: "ecoli_test"
  path: "data/local_genome/local_genome.fna.gz"

variant_calling:
  tool: "gatk"
  gatk:
    min_pruning: 1
    min_dangling: 1
    het_prior: 0.005
    ploidy: 1

intervals:
  enabled: true
  min_nmer: 500
  num_gvcf_intervals: 2
  db_scatter_factor: 0.15

reads:
  mark_duplicates: true
  sort: false

remote_reads:
  enabled: false

callable_sites:
  coverage:
    enabled: false
    stdev: 2
    merge_distance: 100
  mappability:
    enabled: true
    min_score: 1
    kmer: 150
    merge_distance: 100

modules:
  qc:
    enabled: false
  postprocess:
    enabled: false
  trackhub:
    enabled: false
