##############################
# Variables you need to change
##############################

samples: "config/test_coords.csv"            # name of the sample metadata CSV 
tmp_dir: "tmp/"   # directory path for a temp dir 
split_by_n: True    #set to False to split by chromosome/scaffold; set to True to split on runs of Ns within chromosomes/scaffolds.
sentieon: False  #set to True if you want to use sentieon, False if you want GATK
sentieon_lic: "" #set to path of sentieon license
remote_reads: False # set if you want reads to be on google cloud storage remote
remote_reads_prefix: "" # set to google bucket name where reads live
##############################
# Variables you *might* need to change
##############################

# if using the BAM -> VCF workflows
bamsForGatk: "fastq2bam/01_mappedReads/" # directory containing BAMs for GATK. If you used the fastq -> bam workflow above, simply keep the default value; must be followed by a "/"
bamsForFB: "fastq2bam/01_mappedReads/"   # directory containing BAMs for Freebayes. If you used the fastq -> bam workflow above, simply keep the default value; must be followed by a "/"
bam_suffix: "_final.bam"                 # the suffix for your BAM files that follow all the sample names. If you use the fastq->BAM workflow above, simply keep the default value 

# These parameters control how the genome gets split into intervals according to Nmers in the reference genome
maxNumIntervals: 10             # the maximum number of intervals when split_by_n is False. If your reference genome has hundreds of scaffolds, it can be helpful to set this to less than number of scaffolds.
minNmer: 500                    # the minimum Nmer used to split up the genome; e.g. a value of 200 means only Nmers 200 or greater are used to define the boundaries of intervals. The minimum is 50.
maxIntervalLen: 15000000          # the desired maximum size of an interval for calling variants; more than 2Mb is a good starting point
maxBpPerList: 15000000            # the desired maximum number of bp per list file for GATK4; list files potentially contain many small intervals, and we cap the fraction of the genome contained in each list file here
maxIntervalsPerList: 200        # the desired maximum number of intervals per list file for GATK4; this prevents list files from containing thousands of small intervals, which can slow parts of GATK4. Default is good.
maxDP_fb: 200 # this is the maximum depth parameter used for freebayes, site with more than this number are ignored, change according to expected depth

## Coverage options ##
## default pipeline is optimized for low coverage data - if using high coverage data (> 10x), uncomment high coverage options and comment out low coverage options

# low coverage options (< 10x) 
minP: 1
minD: 1

# high coverage options (> 10x)
#minP: 2
#minD: 4

## QC options ##
nClusters: 3

##############################
# Variables you DO NOT need to change
# if you do, ensure all path/directory names are followed by a "/"
# These variables control the output of the fastq2bam workflow. You don't need to change these, but if you do please have a forward slash follow name!
##############################

output: "results/"
fastqDir: "data/fastq/"                           # this is where raw fastqs are downloaded
refGenomeDir: "data/genome/"                      # where reference genomes go
fastq2bamDir: "fastq2bam/"
fastqFilterDir: "00_fastqFiltered/"     # new directory created for filtered fastq reads
bamDir: "01_mappedReads/"               # new directory created for BAM files
sumstatDir: "02_bamSumstats/"           # new directory created for BAM summary statistics

# These variables control the output of the GATK4 workflow (please have forward slash follow name!)
gatkDir: "gatk/"
gvcfDir: "03_gvcfs/"
dbDir: "04_genomicsDB/"
vcfDir_gatk: "05_vcfs/"
qcDir: "06_QC/"
intDir: "intervalFiles/"

# These variables control the output of the FreeBayes workflow (please have forward slash follow name!)   
fbDir: "freebayes/"
intervalDir: "00_intervals/"
vcfDir_fb: "01_vcfs_byinterval/"

#information for read groups
flowcell: "FLOWCELL"
platform: "ILLUMINA"

cluster_config: "profiles/slurm/cluster_config.yml"
test_qc: True
