# snpArcher v2 smoke-test configuration

samples: "config/samples.csv"

reference:
  name: "ecoli_test"
  source: "data/local_genome/local_genome.fna.gz"

reads:
  mark_duplicates: true

variant_calling:
  expected_coverage: "low"
  tool: "gatk"
  ploidy: 1
  gatk:
    het_prior: 0.005
    concat_batch_size: 5
    concat_max_rounds: 20

intervals:
  enabled: true
  min_nmer: 500
  num_gvcf_intervals: 2
  db_scatter_factor: 0.15

callable_sites:
  generate_bed_file: false
  coverage:
    enabled: false
  mappability:
    enabled: true
    kmer: 150
    min_score: 1
    merge_distance: 100

modules:
  qc:
    enabled: false
  postprocess:
    enabled: false
  trackhub:
    enabled: false
  mk:
    enabled: false
