# snpArcher v2 test configuration - CI

samples: "config/samples.csv"

reference:
  name: "yeast_test"
  accession: "GCF_000146045.2"

variant_calling:
  tool: "gatk"
  gatk:
    min_pruning: 1
    min_dangling: 1
    het_prior: 0.005
    ploidy: 2

intervals:
  enabled: true
  min_nmer: 500
  num_gvcf_intervals: 50
  db_scatter_factor: 0.15

reads:
  mark_duplicates: true
  sort: false

remote_reads:
  enabled: false

callable_sites:
  coverage:
    enabled: true
    stdev: 2
    merge_distance: 100
  mappability:
    enabled: true
    min_score: 1
    kmer: 150
    merge_distance: 100

modules:
  qc:
    enabled: false
    clusters: 3
    min_depth: 2
    google_api_key: ""
  postprocess:
    enabled: false
  trackhub:
    enabled: false
