name: Tests

on:
  push:
    paths:
      - "**/Snakefile"
      - "**/*.smk"
      - "**/*.py"
      - "workflow/envs/*.yml"
      - ".github/workflows/*"
  pull_request:
    paths:
      - "**/Snakefile"
      - "**/*.smk"
      - "**/*.py"
      - "workflow/envs/*.yml"
      - ".github/workflows/*"

jobs:
  test-fastq-to-vcf:
    name: Test fastq-to-vcf pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true

      - name: Run test
        run: pixi run test-simple
