
name: Test QC

on: 
  push:
    paths:
      - "workflow/rules/qc.smk"        
jobs:

  Testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test workflow (Local Fastq > VCF)
      uses: snakemake/snakemake-github-action@v1.22.0
      with:
        directory: .test/anemone/
        snakefile: workflow/Snakefile
        args: "--use-conda --show-failed-logs -j 10 --conda-cleanup-pkgs cache --conda-frontend mamba"
